import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/QueryProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import ProviderReducer from "@/components/providers/ProviderReducer";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderReducer
          providers={[QueryProvider, TooltipProvider]}
        >
          {children}
        </ProviderReducer>
        <Toaster />
        <Sonner />
      </body>
    </html>
  );
}
